#         Powered by TabooLib 6.0         #

chat:
  default:
    default-chatcolor: "#cccccc"
    default-namecolor: "#aaaaaa"
  format:
    GROUP: |
      {format-group} {format-title} {format-nick}
      {format-reply}{format-message}
    USER: |
      {format-nick}
      {format-reply}{format-message}
  

title:
  TEMPERATURE:
    content: '{title.temperature}'
    color:
      default: <gray>
      premium: <gradient:#eeeeee:#aaaaaa>
  SPECIAL:
    content: '{title.special}'
    color:
      default: <#ff66cc>
      premium: <gradient:#ff66cc:#cc66ff>
  PERMISSION-ADMINISTRATOR:
    content: 管理员
    color:
      default: <#66ff66>
      premium: <gradient:#66ffcc:#66ff66>
  PERMISSION-BUREAUCRAT:
    content: 行政员
    color:
      default: <#ffcc88>
      premium: <gradient:#ffcc00:#cc6600>
  PERMISSION-OWNER:
    content: 群主
    color:
      default: <#ffff00>
      premium: <gradient:#ffff00:#ff0000>

redis:
  host: localhost
  port: 6379
  auth: root
  pass: root
  connect: 32
  timeout: 1000

datastore:
  use: MYSQL
  # SQLITE,MYSQL

  source: # MySQL
    SQL:
      host: localhost
      port: 3306
      database: chotenchat
      username: root
      password: 123456

lang: zh_CN

debug:
  developer-mode: false

  tolerance-kether: true
  # Kether 宽容解析
  # 默认值 true 不推荐关闭