#         Powered by TabooLib 6.0         #

chat:
  format:
    GROUP: |
      {format-group} {format-title} {format-nick}
      {format-reply}{format-message}
    USER: |
      {format-nick}
      {format-reply}{format-message}
  tolerance-kether: false
  # Kether 宽容解析
  # 默认值 false

title:


redis:
  host: localhost
  port: 6379
  auth: root
  pass: root
  connect: 32
  timeout: 1000

datastore:
  use: MYSQL
  # SQLITE,MYSQL

  source: # MySQL
    SQL:
      host: localhost
      port: 3306
      database: chotenchat
      username: root
      password: 123456

lang: zh_CN

debug:
  developer-mode: false