#         Powered by TabooLib 6.0         #

chat:
  format:
    GROUP: |
      {group} {title} {nick}
      {reply}{format-message}
    USER: |
      {nick}
      {reply}{format-message}
    # 自定义 TODO

  tolerance-kether: false
  # Kether 宽容解析
  # 默认值 false
redis:
  host: localhost
  port: 6379
  # 不设置用户密码则直接注释该选项
  auth: root
  pass: root
  connect: 32
  timeout: 1000

datastore:
  use: MYSQL
  # SQLITE,MYSQL

  source: # MySQL
    SQL:
      host: localhost
      port: 3306
      database: chotenchat
      username: root
      password: 123456

lang: zh_CN

debug:
  developer-mode: false